buildscript {
    repositories {

        maven { url = "https://repo1.maven.org/maven2" }

        jcenter()
        maven { url = "https://maven.minecraftforge.net/" }
    }
    dependencies {
      classpath ('com.anatawa12.forge:ForgeGradle:1.2-1.1.+') {
         changing = true
      }
    }
}

apply plugin: 'forge'

sourceCompatibility = targetCompatibility = "1.7"
compileJava { sourceCompatibility = targetCompatibility = "1.7" }

version = "1.7.10-1.21"
group = "net.montoyo.mcef"
archivesBaseName = "MCEF"

minecraft {
    version = "1.7.10-10.13.4.1614-1.7.10"
}
